# Generated by Django 5.2.1 on 2025-05-26 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itens', '0002_alter_item_quantidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='endereco',
            field=models.CharField(default=0, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
