# Generated by Django 5.2.1 on 2025-05-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itens', '0003_item_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='nota_fiscal',
            field=models.CharField(default=0, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
