# Generated by Django 5.2.1 on 2025-05-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itens', '0004_item_nota_fiscal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='nota_fiscal',
            field=models.CharField(max_length=50),
        ),
    ]
