# Generated by Django 5.2.1 on 2025-05-27 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itens', '0006_notafiscal_alter_item_nota_fiscal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notafiscal',
            old_name='numero',
            new_name='numero_de_nota',
        ),
    ]
