# Generated by Django 5.2.1 on 2025-05-27 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itens', '0007_rename_numero_notafiscal_numero_de_nota'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='nota_fiscal',
        ),
    ]
