# Generated by Django 5.2.1 on 2025-05-27 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itens', '0009_rename_nome_fabricante_nome_do_fabricante'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Item', 'verbose_name_plural': 'Itens'},
        ),
        migrations.AlterModelOptions(
            name='notafiscal',
            options={'verbose_name': 'Nota Fiscal', 'verbose_name_plural': 'Notas Fiscais'},
        ),
    ]
