# Generated by Django 5.2.1 on 2025-05-28 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itens', '0011_alter_item_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='sku',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
