# Generated by Django 5.2.1 on 2025-05-28 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itens', '0012_item_sku'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notafiscal',
            options={'verbose_name': 'Origem', 'verbose_name_plural': 'Origem'},
        ),
    ]
