# Generated by Django 5.2.1 on 2025-05-28 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itens', '0013_alter_notafiscal_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notafiscal',
            name='numero_de_nota',
            field=models.CharField(max_length=50, verbose_name='Tipo de Origem'),
        ),
    ]
