# Generated by Django 5.2.1 on 2025-05-28 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itens', '0014_alter_notafiscal_numero_de_nota'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='valor_atual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor Hoje'),
            preserve_default=False,
        ),
    ]
