# Generated by Django 5.2.1 on 2025-05-28 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itens', '0015_item_valor_atual'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoValorItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_anterior', models.DecimalField(decimal_places=2, max_digits=15)),
                ('valor_novo', models.DecimalField(decimal_places=2, max_digits=15)),
                ('data_alteracao', models.DateTimeField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_valores', to='itens.item')),
            ],
        ),
    ]
