# Generated by Django 5.2.1 on 2025-05-28 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itens', '0017_item_modelo_alter_item_partnumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='modelo',
        ),
    ]
