# Generated by Django 5.2.1 on 2025-05-28 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itens', '0018_remove_item_modelo'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='modelo',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
