# Generated by Django 5.2.1 on 2025-05-29 11:57

import itens.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itens', '0020_historicovaloritem_responsavel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='img',
            field=models.ImageField(blank=True, upload_to='itens/', validators=[itens.validators.validar_tamanho_imagem]),
        ),
    ]
