# Generated by Django 5.2.1 on 2025-05-31 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itens', '0021_alter_item_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='ultima_saida',
            field=models.DateField(blank=True, null=True),
        ),
    ]
