# Generated by Django 5.2.1 on 2025-05-27 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrada_de_itens', '0002_entrada_responsavel'),
        ('itens', '0008_remove_item_nota_fiscal'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='nota_fiscal',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='itens.notafiscal'),
            preserve_default=False,
        ),
    ]
