# Generated by Django 5.2.1 on 2025-05-28 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrada_de_itens', '0003_entrada_nota_fiscal'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='cotacao_atual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Cotação Atual'),
            preserve_default=False,
        ),
    ]
