# Generated by Django 5.2.1 on 2025-05-28 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrada_de_itens', '0004_entrada_cotacao_atual'),
        ('itens', '0013_alter_notafiscal_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='nota_fiscal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itens.notafiscal', verbose_name='Origem'),
        ),
    ]
