# Generated by Django 5.2.1 on 2025-05-26 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fabricante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('partnumber', models.CharField(max_length=50, unique=True)),
                ('img', models.ImageField(upload_to='itens/')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('disponivel', models.BooleanField(default=False)),
                ('fabricante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itens.fabricante')),
            ],
        ),
    ]
