# Generated by Django 5.2.1 on 2025-05-27 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saida_de_itens', '0002_saida_responsavel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destinatario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='saida',
            name='destino',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='saida_de_itens.destinatario'),
            preserve_default=False,
        ),
    ]
